
using Microsoft.Xna.Framework;
using StardewModdingAPI;
using System.Collections.Generic;

namespace SGJigsaw
{
    public class ModConfig
    {
        public bool ModEnabled { get; set; } = true;
        public bool FuseConnected { get; set; } = true;
        public bool ShuffleMusic { get; set; } = false;
        //public bool ShowOutlines { get; set; } = true;
        //public int OutlineThickness { get; set; } = 4;
        //public Color OutlineColor { get; set; } = Color.LightGray;
        public SButton SnapKey { get; set; } = SButton.LeftShift;
        public SButton SolveKey { get; set; } = SButton.End;
        public bool Snap { get; set; } = false;
        public bool PlayingMusic { get; set; } = true;
        public string CurrentMusic { get; set; } = "MainTheme";
        public string SnapSound { get; set; } = "newArtifact";
        public string SolveSound { get; set; } = "yoba";
        public List<string> Music { get; set; } = new List<string>()
        {
            "50s",
            "AbigailFlute",
            "AbigailFluteDuet",
            "aerobics",
            "archaeo",
            "bigDrums",
            "breezy",
            "caldera",
            "Cavern",
            "christmasTheme",
            "Cloth",
            "CloudCountry",
            "clubloop",
            "cowboy_boss",
            "cowboy_outlawsong",
            "Cowboy_OVERWORLD",
            "Cowboy_singing",
            "Cowboy_undead",
            "crane_game",
            "crane_game_fast",
            "Crystal Bells",
            "Cyclops",
            "desolate",
            "distantBanjo",
            "EarthMine",
            "echos",
            "elliottPiano",
            "EmilyDance",
            "EmilyDream",
            "EmilyTheme",
            "end_credits",
            "event1",
            "event2",
            "fall1",
            "fall2",
            "fall3",
            "fallFest",
            "fieldofficeTentMusic",
            "FlowerDance",
            "FrogCave",
            "FrostMine",
            "FrostMine",
            "FrostMine",
            "Ghost Synth",
            "grandpas_theme",
            "gusviolin",
            "harveys_theme_jazz",
            "heavy",
            "honkytonky",
            "Icicles",
            "IslandMusic",
            "jaunty",
            "junimoKart",
            "junimoKart_ghostMusic",
            "junimoKart_mushroomMusic",
            "junimoKart_slimeMusic",
            "junimoKart_whaleMusic",
            "junimoStarSong",
            "kindadumbautumn",
            "LavaMine",
            "libraryTheme",
            "MainTheme",
            "Majestic",
            "MarlonsTheme",
            "marnieShop",
            "mermaidSong",
            "moonlightJellies",
            "movie_classic",
            "movie_nature",
            "movie_wumbus",
            "movieTheater",
            "movieTheaterAfter",
            "musicboxsong",
            "Near The Planet Core",
            "New Snow",
            "night_market",
            "Of Dwarves",
            "Orange",
            "Overcast",
            "Pink Petals",
            "PIRATE_THEME",
            "PIRATE_THEME(muffled)",
            "playful",
            "Plums",
            "poppy",
            "raccoonSong",
            "ragtime",
            "sad_kid",
            "sadpiano",
            "Saloon1",
            "sam_acoustic1",
            "sam_acoustic2",
            "sampractice",
            "sappypiano",
            "Secret Gnomes",
            "SettlingIn",
            "shaneTheme",
            "shimmeringbastion",
            "spaceMusic",
            "spirits_eve",
            "spring1",
            "spring2",
            "spring3",
            "springsongs",
            "springsongs",
            "springsongs",
            "springtown",
            "Stadium_ambient",
            "starshoot",
            "submarine_song",
            "summer1",
            "summer2",
            "summer3",
            "SunRoom",
            "sweet",
            "tickTock",
            "tinymusicbox",
            "title_night",
            "tribal",
            "Tropical Jam",
            "VolcanoMines",
            "VolcanoMines1",
            "VolcanoMines2",
            "wavy",
            "wedding",
            "winter1",
            "winter2",
            "winter3",
            "WizardSong",
            "woodsTheme",
            "XOR",
            "decimal",
            "babblingBrook",
            "bugLevelLoop",
            "communityCenter",
            "cracklingFire",
            "darkCaveLoop",
            "fall_day_ambient",
            "Frost_Ambient",
            "heavyEngine",
            "Hospital_Ambient",
            "jojaOfficeSoundscape",
            "jungle_ambience",
            "Lava_Ambient",
            "movieScreenAmbience",
            "nightTime",
            "ocean",
            "pool_ambient",
            "rain",
            "roadnoise",
            "spring_day_ambient",
            "spring_night_ambient",
            "summer_day_ambient",
            "tropical_island_day_ambient",
            "Upper_Ambient",
            "Volcano_Ambient",
            "waterfall",
            "waterfall_big",
            "wind",
            "winter_day_ambient",
        };
    }
}
